### ISSUE TITLE
Chrome WebGL issues warnings that can cause the particle system to fail to restart.

### ISSUE THREAD

**Issue by insominx** [mkkellogg/ParticleSystemJS#2]
Chrome WebGL issues warnings that can cause the particle system to fail when using release all once systems with particleLifeSpan <= lifespan.

Chrome has this in the console:
 [.CommandBufferContext]RENDER WARNING: Render count or primcount is 0.

Example attached
[problem-example.zip](https://github.com/mkkellogg/Photons/files/180055/problem-example.zip)

Notice the values here:

```
    particleSystemParams = {

        material: smokeMaterial,
        particleAtlas : photonAtlas,            
        particleLifeSpan : 1, 
        lifespan : 2,
        zsort: false,
        releaseAtOnce: true,
        releaseAtOnceCount: 50,
        simulateInLocalSpace: false

    };
```

particleLifeSpan is 1 and lifespan is 2.  The error will still occur even if particleLifeSpan is 2.  The odd fix here is to make particleLifeSpan equal to 2.01 (or something greater)

**Comment by mkkellogg** [comment]
This looks like a bug in my code, I'll look into it (once I have a spare moment) to see if I can figure out what's happening.

**Comment by mkkellogg** [comment]
After a quick check, I don't seem to be encountering this problem on my machine. I'm using the latest release of three.js (r75) so I wonder if that has something to do with it. With which version are you currently developing?

**Comment by insominx** [comment]
Yup, it's using r75.  You can see it from the printout in the console (from problem-example.zip).  I also test with the dev version though it isn't all that much different at this point.

**Comment by mkkellogg** [comment]
Hmmm, I wonder if it's specific to the version of Chrome you are using? It might be that the error condition still exists with my version, and that Chrome is simply handling it more elegantly (quietly).

I'm guessing the problem arises when there are zero particles to be rendered, but Three.js is issuing draw calls regardless. In that case we may want to update ParticleSystem.js at line 502 where it reads:

``` javascript
this.particleGeometry.setDrawRange( 0, PHOTONS.Constants.VerticesPerParticle * this.liveParticleCount );
```

by adding a check for `this.liveParticleCount === 0` and disabling rendering for the particle system in that case.

**Comment by insominx** [comment]
I see the issue on both my windows and mac machine - Chrome.  And your fix worked:

```
if ( this.liveParticleCount > 0 )
    this.particleGeometry.setDrawRange( 0, PHOTONS.Constants.VerticesPerParticle * this.liveParticleCount );
```

**Comment by insominx** [comment]
I've added this to #1
